### ISSUE TITLE
[Bug]: 静态首页官网挂掉了

### ISSUE THREAD

**Issue by ONLY-yours** [oceanbase/oceanbase-design#1]
https://design.oceanbase.com/ 
官网链接挂掉了

**Comment by dengfuping** [comment]
域名配置问题，已修复，可以正常访问了 https://design.oceanbase.com/

![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/4fb32864-53f5-491a-b51c-65537b7413fd)
