### ISSUE TITLE
[Question]: BasicLayout使用时路由跳转侧边导航栏没有响应

### ISSUE THREAD

**Issue by yang1666204** [oceanbase/oceanbase-design#362]
### 描述
我遇到一个问题，在使用obui的BasicLayout组件时，路由跳转后侧边导航栏的选中效果没有更新，貌似obui没有监听到路由的跳转，并且defaultSelectedKeys属性貌似也没有生效

### 重现步骤

1. 进入页面A
2. 点击按钮to B
3. 观察到页面更新，但是侧边导航栏没有更新

### 预期行为
预期的行为是侧边导航栏的选中态跟随路由跳转变化

### 可重现的演示
demo示例:https://codesandbox.io/p/sandbox/oceanbase-design-reproduction-template-forked-779m3k?file=%2Findex.js%3A22%2C13

### 环境
@umijs/max：4.0.72
@oceanbase/ui：0.2.13

**Comment by dengfuping** [comment]
需要设置 BasicLayout 的 location 属性才能实现当前路由和选中菜单项的联动
