### ISSUE TITLE
[Bug]: ui-introduce 页面内的sanbox中的例子运行报错

### ISSUE THREAD

**Issue by custs21113** [oceanbase/oceanbase-design#43]
**Describe the bug**

打开官网发现这个部分是这样的
![image](https://github.com/oceanbase/oceanbase-design/assets/38849744/b4941e29-2009-40f6-9d16-c8f4c94283fe)
![image](https://github.com/oceanbase/oceanbase-design/assets/38849744/61fd828c-62f2-453d-bd8d-b3aa071b1dc7)

**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- Component Version: 0.2.12
  

**Fast Reproduce Steps(Required)**

Steps to reproduce the behavior: https://codesandbox.io/s/oceanbase-ui-reproduction-template-cknd9y

**Expected behavior**

**Actual Behavior**

![image](https://github.com/oceanbase/oceanbase-design/assets/38849744/a673c5f9-6e12-43df-b0cd-688e00224fc1)

**Additional context**

**Comment by any1024** [comment]
试了下

**Comment by dengfuping** [comment]
- 已在 #64 中去掉了 `@oceanbase/ui` 的 `react-router-dom` 依赖，改为了通过 `ConfigProvider` 全局注入 `navigate` 路由跳转函数。CodeSandbox 示例已经可以正常展示 https://codesandbox.io/s/oceanbase-ui-reproduction-template-cknd9y?file=/index.js。

![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/9a49cae5-9e6e-4bf1-b6f4-42e800ce0077)
