### ISSUE TITLE
[Doc]: repetitive description

### ISSUE THREAD

**Issue by wzc520pyfm** [oceanbase/oceanbase-design#7]
The description of the component is repeated in the official documentation, see: [Example](https://design.oceanbase.com/biz-components/fullscreen-box).

The reason may be `.dumi/theme/slots/Content/index.tsx 270`.
```ts
{!meta.frontmatter.__autoDescription && meta.frontmatter.description}
```

**Comment by dengfuping** [comment]
> The description of the component is repeated in the official documentation, see: [Example](https://design.oceanbase.com/biz-components/fullscreen-box).
> 
> The reason may be `.dumi/theme/slots/Content/index.tsx 270`.
> 
> ```ts
> {!meta.frontmatter.__autoDescription && meta.frontmatter.description}
> ```

- 👏🏻 PR Welcome.

**Comment by wzc520pyfm** [comment]
I do not know the purpose of this line of code, my current solution is to delete this line of code, is this feasible?

**Comment by dengfuping** [comment]
> I do not know the purpose of this line of code, my current solution is to delete this line of code, is this feasible?

- Yeah, it's OK. `meta.frontmatter.description` is not usable for now.
